version: '3.8'

services:
  youtube-scraper-api:
    build: .
    container_name: youtube-scraper-api
    ports:
      - "8000:8000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - youtube-scraper-network

networks:
  youtube-scraper-network:
    driver: bridge

volumes:
  logs:
    driver: local
